feat: ability to import wallet by private key and WIF
ArkEcosystem/ark-desktop pull request #3483
Opened 2021-03-11 16:07 UTC by luciorubeens

## Summary

https://app.clickup.com/t/3k6ygq

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2021-03-11 16:48 UTC, faustbrian commented on src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
> +				wallet = await activeProfile.wallets().importByPrivateKey(network.coin(), network.id(), privateKey);
I'll add a method tomorrow to directly import by WIF. It already exists but isn't exported.

2021-03-12 04:58 UTC, faustbrian requested changes
Please split this into a PR for private key import and another for WIF.

2021-03-12 05:56 UTC, faustbrian commented
> https://github.com/ArkEcosystem/platform-sdk/releases/tag/3.1.20

This release contains 2 methods to import a plain WIF and a BIP38 encrypted WIF. Please submit 2 separate PRs for those and keep this one limited to private key import.

2021-03-12 14:18 UTC, samharperpittam approved these changes

2021-03-12 14:26 UTC, faustbrian approved these changes

2021-03-12 14:26 UTC, merged