feat: import wallet by WIF and encrypted WIF
ArkEcosystem/ark-desktop pull request #3491
Opened 2021-03-12 19:00 UTC by luciorubeens

## Summary

https://app.clickup.com/t/3q40ag

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [x] The change is not hardcoded to a single network, but has multi-asset in mind
-   [x] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [x] Tests _(if necessary)_
-   [x] Ready to be merged

2021-03-13 01:40 UTC, faustbrian requested changes, later dismissed
Please split this into a separate PRs as requested because those are separate features.

2021-03-15 11:07 UTC, samharperpittam requested changes
@luciorubeens - Using my WIF does import my wallet correctly. However, if I enter a load of random characters on the import page with either 'WIF' or 'Private Key' selected I get the following errors. 

`Unhandled Rejection (CryptoException): Invalid checksum`

2021-03-15 15:21 UTC, luciorubeens commented
@samharperpittam fixed

2021-03-15 16:14 UTC, samharperpittam approved these changes

2021-03-17 15:44 UTC, ItsANameToo approved these changes

2021-03-17 15:44 UTC, merged