refactor: remove recipients/participants based on index
ArkEcosystem/ark-desktop pull request #3492
Opened 2021-03-12 20:37 UTC by dated

## Summary

https://app.clickup.com/t/fk5d5w

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [x] Tests _(if necessary)_
-   [x] Ready to be merged

2021-03-12 20:37 UTC, faustbrian commented
Task linked: [CU-fk5d5w [Multipay] removing a recipient matches against address only](https://app.clickup.com/t/fk5d5w)

2021-03-15 12:34 UTC, samharperpittam requested changes
Seeing odd behaviour on this PR still. Video sent via Slack.

2021-03-15 12:39 UTC, samharperpittam approved these changes, later dismissed

2021-03-15 13:13 UTC, samharperpittam approved these changes

2021-03-15 13:26 UTC, ItsANameToo approved these changes

2021-03-15 13:26 UTC, merged